language: node_js
node_js:
  - "4"
  - "0.12"
install: 
  - npm i -g eslint croc
script:
  - croc link
  - croc install
  - croc-cli/bin/croc-cli.js ls
  - croc-cli/bin/croc-cli.js deps
  - croc-cli/bin/croc-cli.js link
  - croc-cli/bin/croc-cli.js install
  - croc-cli/bin/croc-cli.js build
  - croc-cli/bin/croc-cli.js test
